Dembed2 Domain
Gujal00/ResolveURL pull request #182
Opened 2022-08-22 02:19 UTC by cywteow

Added a resolver for Dembed2 Domain

2022-08-22 03:38 UTC, Gujal00 requested changes
Thanks mate, there are a couple of issues with this PR as ResolveURL doesn't include requests library and also the use of urllib.parse which makes PY3 only.

If you want I can redo the plugin based on your code in a compliant way. Thanks

2022-08-22 03:38 UTC, Gujal00 commented on script.module.resolveurl/lib/resolveurl/plugins/dembed.py
> +import requests
ResolveURL doesnt include requests module.

2022-08-22 03:38 UTC, Gujal00 commented on script.module.resolveurl/lib/resolveurl/plugins/dembed.py
> +        response = requests.get(web_url, headers={"X-Requested-With":"XMLHttpRequest"})
need to be done with the net module

2022-08-22 03:38 UTC, Gujal00 commented on script.module.resolveurl/lib/resolveurl/plugins/dembed.py
> +        if response.status_code == 200:
same as above

2022-08-22 03:38 UTC, Gujal00 commented on script.module.resolveurl/lib/resolveurl/plugins/dembed.py
> +            encryptedResult = response.json()
jason.loads as requests module not available

2022-08-22 03:38 UTC, Gujal00 commented on script.module.resolveurl/lib/resolveurl/plugins/dembed.py
> +from urllib.parse import urlsplit, parse_qs, urlparse
use six.moves as this will break Kodi <19 support currently in ResolveURL

2022-08-22 04:43 UTC, cywteow commented
> Thanks mate, there are a couple of issues with this PR as ResolveURL doesn't include requests library and also the use of urllib.parse which makes PY3 only.
> 
> If you want I can redo the plugin based on your code in a compliant way. Thanks

Can you make the changes for me as Python is not my main language. Thank you for your time.

2022-08-22 22:35 UTC, Gujal00 commented
Closing this PR as the code has been rewritten to work on py2 and 3 in https://github.com/Gujal00/ResolveURL/commit/605094bf2d389fb0625f58d3be40c451af0f3518

2022-08-22 22:35 UTC, closed without merging

2022-08-22 23:37 UTC, shellc0de27 commented
@Gujal00 Just a thought.....
This is a vidcloud9 domain can just be added to `vidcloud9.py` without even modifying headers as you can see below.
`SMR Link Tester: Link Supported: |https://dembed2.com/streaming.php?id=MzY3NjUy&title=American+Pickers+-+Season+23+Episode+17+-+Knucklehead+Blue&typesub=SUB&sub=&cover=Y292ZXIvYW1lcmljYW4tcGlja2Vycy1zZWFzb24tMjMucG5n| Resolvers: VidCloud9
SMR Link Tester: Link Resolved: |https://dembed2.com/streaming.php?id=MzY3NjUy&title=American+Pickers+-+Season+23+Episode+17+-+Knucklehead+Blue&typesub=SUB&sub=&cover=Y292ZXIvYW1lcmljYW4tcGlja2Vycy1zZWFzb24tMjMucG5n|https://hls3x.vidfiles.net/videos/hls/njCuYAEM5HGEEbpb1TSBsw/1661225521/367652/951a17ecbd942e39fa18883f9c1cfcee/ep.17.v0.1661130646.m3u8|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A68.0%29+Gecko%2F20100101+Firefox%2F68.0&Referer=https%3A%2F%2Fmembed.net%2Floadserver.php%3Fid%3DMzY3NjUy|`

2022-08-23 00:23 UTC, Gujal00 commented
@shellc0de27 i did check it, but as the key and iv are different and even the resolved file is different, I added the new one
```INFO <general>: SMR Link Tester: Playing Link: |https://dembed2.com/streaming.php?id=MzM4MjU0&title=Immortal+Samsara+%282022%29+episode+15&typesub=SUB|
INFO <general>: SMR Link Tester: Link Supported: |https://dembed2.com/streaming.php?id=MzM4MjU0&title=Immortal+Samsara+%282022%29+episode+15&typesub=SUB| Resolvers: dembed2
INFO <general>: SMR Link Tester: Link Resolved: |https://dembed2.com/streaming.php?id=MzM4MjU0&title=Immortal+Samsara+%282022%29+episode+15&typesub=SUB|https://cache.387e6278d8e06083d813358762e0ac63.com/222835338184.m3u8|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A68.0%29+Gecko%2F20100101+Firefox%2F68.0|```
Try that link above in browser and see what it plays and try with vidcloud9 resolver and see what it plays

2022-08-23 00:29 UTC, shellc0de27 commented
Oh snap completely different. wow....

2022-08-23 00:37 UTC, Gujal00 commented
@shellc0de27 yep looks like dembed2 site logic is just a clone of membed, but the actual media_ids and streams are different :)

2022-08-23 00:42 UTC, shellc0de27 commented
@Gujal00 Awesome catch bro :)

2022-08-23 00:53 UTC, shellc0de27 commented
Thanks for also clarifying. Was thinking to save time when they change and only updating once vs twice. But yeah their different :P