Fix doodstream
Gujal00/ResolveURL pull request #294
Opened 2023-01-03 18:22 UTC by alpha7504

2023-01-03 21:58 UTC, Gujal00 requested changes

2023-01-03 21:58 UTC, Gujal00 commented on script.module.resolveurl/lib/resolveurl/plugins/doodstream.py
> +        if host.endswith('.wf'):
you need to add checking for `.wf` and not just replace `.cx` as that is still required
`if any(host.endswith(x) for x in ['.cx', '.wf']):` will do the job

2023-01-04 03:24 UTC, alpha7504 commented
Thanks for pointing that out.

2023-01-04 06:00 UTC, merged

2023-01-04 15:55 UTC, bleak-lodge commented
Just a cosmetic note here, that `endswith()` also takes a tuple, don't have to use `any()` ;)

2023-01-05 13:19 UTC, bleak-lodge commented
value can be a tuple, so `host.endswith(('.cx', '.wf'))` should do the same thing as with any()
https://docs.python.org/3/library/stdtypes.html#string-methods

2023-01-06 06:34 UTC, alpha7504 commented
Should I make this change? or leave it be